apiVersion: apps/v1
kind: Deployment
metadata:
  name: nana-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080
